version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
      - web-media:/usr/src/app/media
      - /var/certbot/conf:/etc/letsencrypt
    env_file: .env
    command: /usr/local/bin/gunicorn --config gunicorn_config.py lexcredendi.wsgi:application

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-static:/www/static
      - web-media:/www/media
      - /var/certbot/conf:/etc/letsencrypt
      - /var/certbot/www/:/var/www/certbot
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: .env

  certbot:
    build: ./certbot/
    volumes:
      - /var/certbot/conf:/etc/letsencrypt
      - /var/certbot/www/:/var/www/certbot
    depends_on:
      - nginx

volumes:
  web-django:
  web-static:
  web-media:
  pgdata: