version: '3'

services:
  django:
    restart: always
    build: ./django
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - django-appp:/usr/src/app
      - django-static:/usr/src/app/static
      - django-media:/usr/src/app/media
      - certbot-conf:/etc/letsencrypt
    env_file: .env
    command: /usr/local/bin/gunicorn --config gunicorn_config.py lexcredendi.wsgi:application

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - django-static:/www/static
      - django-media:/www/media
      - certbot-conf:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    links:
      - django:django

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file: .env

  certbot:
    build: ./certbot/
    volumes:
      - certbot-conf:/var/certbot/conf
      - certbot-www:/var/www/certbot
    depends_on:
      - nginx

volumes:
  django-appp:
  django-static:
  django-media:
  postgres-data:
  certbot-conf:
  certbot-www: