version: '3'

services:
  web:
    restart: always
    build: ./web
    expose:
      - "8000"
    links:
      - postgres:postgres
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
      - web-media:/usr/src/app/media
      - /var/certbot/conf:/etc/letsencrypt/:ro
    env_file: .env
    command: /usr/local/bin/gunicorn --config gunicorn_config.py lexcredendi.wsgi:application

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/www/static
      - web-media:/www/media
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file: .env

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - /var/certbot/conf:/etc/letsencrypt/:rw
  #     - /var/certbot/www/:/var/www/certbot/:rw
  #   depends_on:
  #     - nginx

volumes:
  web-django:
  web-static:
  web-media:
  pgdata: