FROM certbot/certbot:latest

# TODO: comment these lines when requesting a new certificate
COPY fullchain.pem /var/certbot/conf/live/lexcredendi.us.to/fullchain.pem
COPY privkey.pem /var/certbot/conf/live/lexcredendi.us.to/privkey.pem