FROM certbot/certbot:latest

# TODO: comment these lines when requesting a new certificate
COPY fullchain.pem /var/certbot/conf/live/lexcredendi.ignorelist.com/fullchain.pem
COPY privkey.pem /var/certbot/conf/live/lexcredendi.ignorelist.com/privkey.pem