FROM certbot/certbot:latest

# TODO: comment these lines when requesting a new certificate
COPY fullchain.pem /etc/letsencrypt/live/lexcredendi.app/fullchain.pem
COPY privkey.pem /etc/letsencrypt/live/lexcredendi.app/privkey.pem