# Generated by Django 3.0 on 2019-12-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Code')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('album', models.CharField(max_length=255, verbose_name='Collection')),
                ('work', models.ImageField(upload_to='art/', verbose_name='Artwork')),
                ('artist', models.CharField(blank=True, max_length=255, null=True, verbose_name='Artist')),
                ('rough_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
    ]
