# Generated by Django 5.0 on 2023-12-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('album', models.CharField(max_length=255, verbose_name='Album')),
                ('album_title', models.CharField(max_length=255, verbose_name='Album Title')),
                ('image', models.ImageField(upload_to='art/img', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
    ]
