# Generated by Django 3.0 on 2019-12-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20191214_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='filename',
            field=models.CharField(default='test.jpg', max_length=255, primary_key=True, serialize=False, verbose_name='Filename'),
        ),
    ]
