# Generated by Django 3.0 on 2019-12-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('art', '0002_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('filename', models.CharField(default='test.jpg', max_length=255, primary_key=True, serialize=False, verbose_name='Filename')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('album', models.CharField(max_length=255, verbose_name='Album')),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
    ]
