# Generated by Django 3.0 on 2019-12-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='filename',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Filename'),
        ),
    ]
