# Generated by Django 3.0 on 2019-12-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20191214_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='album_title',
            field=models.CharField(default='Test', max_length=255, verbose_name='Album Title'),
        ),
    ]
