# Generated by Django 3.0 on 2019-12-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_record_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='album_title',
            field=models.CharField(max_length=255, verbose_name='Album Title'),
        ),
    ]
