# Generated by Django 5.0 on 2023-12-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_auto_20191215_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='file',
            field=models.FileField(default=None, upload_to='art', verbose_name='File'),
            preserve_default=False,
        ),
    ]
