# Generated by Django 5.0 on 2023-12-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_record_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='file',
        ),
        migrations.AddField(
            model_name='record',
            name='img_file',
            field=models.FileField(default=None, upload_to='img', verbose_name='File'),
            preserve_default=False,
        ),
    ]
