# Generated by Django 5.0 on 2023-12-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_remove_record_file_record_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='img_file',
            field=models.FileField(upload_to='img', verbose_name='Image File'),
        ),
    ]
