# Generated by Django 5.0 on 2023-12-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_remove_record_img_file_record_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='filename',
        ),
        migrations.AddField(
            model_name='record',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
