# Generated by Django 3.0 on 2019-12-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Code')),
                ('english_title', models.CharField(max_length=255, verbose_name='English Title')),
                ('english_text', models.CharField(max_length=4000, verbose_name='English Text')),
                ('english_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='English Comment')),
                ('latin_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latin Title')),
                ('latin_text', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Latin Text')),
                ('latin_comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Latin omment')),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
    ]
