# Generated by Django 3.0 on 2019-12-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='english_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='english_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='record',
            name='english_comment',
        ),
        migrations.RemoveField(
            model_name='record',
            name='latin_comment',
        ),
    ]
