# Generated by Django 3.0 on 2019-12-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0002_auto_20191211_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.CharField(max_length=4000, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
