# Generated by Django 5.0 on 2023-12-28 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Code')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.CharField(max_length=4000, verbose_name='Text')),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
    ]
