FROM nginx

# TODO: uncomment this line when encryption is active
# COPY nginx_https.conf /etc/nginx/conf.d/default.conf

# TODO: comment this line when encryption is active
COPY nginx_http.conf /etc/nginx/conf.d/default.conf