FROM nginx

# TODO: comment this line when requesting a new certificate
# TODO: uncomment this line once SSL is active
COPY nginx_https.conf /etc/nginx/conf.d/default.conf

# TODO: uncomment this line when requesting a new certificate
# TODO: comment this line once SSL is active
# COPY nginx_http.conf /etc/nginx/conf.d/default.conf