FROM nginx

# TODO: uncomment this line once SSL is active
COPY nginx_https.conf /etc/nginx/conf.d/default.conf

# TODO: comment this line once SSL is active
# COPY nginx_http.conf /etc/nginx/conf.d/default.conf